package controller;

import helper.PasswordHasher;
import helper.SessionManager;
import model.Customer;
import repository.CustomerRepository;
import repository.CustomerBalanceRepository; // <-- TAMBAHKAN IMPORT INI

public class CustomerController {

    CustomerRepository repo = new CustomerRepository();
    CustomerBalanceRepository balanceRepo = new CustomerBalanceRepository(); // <-- TAMBAHKAN BARIS INI

    public boolean register(String fullName, String email, String password, String phone, String address, String gender) {
        // Check if email already exists
        if (repo.emailExists(email)) {
            return false;
        }

        // Hash the password before storing
        String hashedPassword = PasswordHasher.hashPassword(password);

        if (hashedPassword == null) {
            return false;
        }

        // Create customer object with id = 0 (will be auto-generated by database)
        Customer customerRegist = new Customer(0, fullName, email, hashedPassword, phone, address, gender);

        // Insert customer into database
        boolean success = repo.insertCustomer(customerRegist);

        // Jika berhasil register, buat saldo awal 0
        if (success) {
            Customer newCustomer = repo.getCustomerByEmail(email); // ambil ID user yang baru
            if (newCustomer != null) {
                balanceRepo.getBalance(newCustomer.getId()); // create saldo 0 otomatis jika belum ada
            }
        }

        return success;
    }

    public boolean login(String email, String password) {
        Customer customer = repo.getCustomerByEmail(email);

        if (customer == null) {
            return false;
        }

        if (PasswordHasher.verifyPassword(password, customer.getPassword())) {
            SessionManager.getInstance().setCurrentCustomer(customer);
            return true;
        }

        return false;
    }

    public void logout() {
        SessionManager.getInstance().logout();
    }

    public boolean updateProfile(String fullName, String email, String newPassword, String phone, String address, String gender) {
        Customer current = SessionManager.getInstance().getCurrentCustomer();
        if (current == null) {
            return false;
        }

        String passwordToPersist = current.getPassword();
        if (newPassword != null && !newPassword.isBlank()) {
            String hashed = PasswordHasher.hashPassword(newPassword);
            if (hashed == null) {
                return false;
            }
            passwordToPersist = hashed;
        }

        Customer updated = new Customer(
                current.getId(),
                fullName,
                email,
                passwordToPersist,
                phone,
                address,
                gender
        );

        boolean success = repo.updateCustomer(updated);
        if (success) {
            SessionManager.getInstance().setCurrentCustomer(updated);
        }
        return success;
    }
}
