package controller;

import helper.PasswordHasher;
import helper.SessionManager;
import model.Customer;
import repository.CustomerRepository;

public class CustomerController {

	CustomerRepository repo = new CustomerRepository();
	
	public boolean register(String fullName, String email, String password, String phone, String address, String gender) {
		// Check if email already exists
		if (repo.emailExists(email)) {
			return false;
		}
		
		// Hash the password before storing
		String hashedPassword = PasswordHasher.hashPassword(password);
		
		if (hashedPassword == null) {
			return false;
		}
		
		// Create customer object with id = 0 (will be auto-generated by database)
		Customer customerRegist = new Customer(0, fullName, email, hashedPassword, phone, address, gender);
		
		// Insert customer into database
		return repo.insertCustomer(customerRegist);
	}
	
	public boolean login(String email, String password) {
		// Get customer by email
		Customer customer = repo.getCustomerByEmail(email);
		
		if (customer == null) {
			return false;
		}
		
		// Verify password
		if (PasswordHasher.verifyPassword(password, customer.getPassword())) {
			// Set session
			SessionManager.getInstance().setCurrentCustomer(customer);
			return true;
		}
		
		return false;
	}
	
	public void logout() {
		SessionManager.getInstance().logout();
	}
	
	public boolean updateProfile(String fullName, String email, String newPassword, String phone, String address, String gender) {
		Customer current = SessionManager.getInstance().getCurrentCustomer();
		if (current == null) {
			return false;
		}
		
		String passwordToPersist = current.getPassword();
		if (newPassword != null && !newPassword.isBlank()) {
			String hashed = PasswordHasher.hashPassword(newPassword);
			if (hashed == null) {
				return false;
			}
			passwordToPersist = hashed;
		}
		
		Customer updated = new Customer(
			current.getId(),
			fullName,
			email,
			passwordToPersist,
			phone,
			address,
			gender
		);
		
		boolean success = repo.updateCustomer(updated);
		if (success) {
			SessionManager.getInstance().setCurrentCustomer(updated);
		}
		return success;
	}
	
}
