package controller;

import helper.PasswordHasher;
import helper.SessionManager;
import model.Customer;
import repository.CustomerRepository;

public class CustomerController {

	CustomerRepository repo = new CustomerRepository();
	
	public boolean register(String fullName, String email, String password, String phone, String address, String gender) {
		// Check if email already exists
		if (repo.emailExists(email)) {
			return false;
		}
		
		// Hash the password before storing
		String hashedPassword = PasswordHasher.hashPassword(password);
		
		if (hashedPassword == null) {
			return false;
		}
		
		// Create customer object with id = 0 (will be auto-generated by database)
		Customer customerRegist = new Customer(0, fullName, email, hashedPassword, phone, address, gender);
		
		// Insert customer into database
		return repo.insertCustomer(customerRegist);
	}
	
	public boolean login(String email, String password) {
		// Get customer by email
		Customer customer = repo.getCustomerByEmail(email);
		
		if (customer == null) {
			return false;
		}
		
		// Verify password
		if (PasswordHasher.verifyPassword(password, customer.getPassword())) {
			// Set session
			SessionManager.getInstance().setCurrentCustomer(customer);
			return true;
		}
		
		return false;
	}
	
	public void logout() {
		SessionManager.getInstance().logout();
	}
	
}
